spring:  
  application:
    name: customer-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.uuid}
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG 

server:
  port: 10200
