spring:  
  application:
    name: account-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      config:
        fail-fast: false
      discovery:
        failFast: false
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
  output.ansi.enabled: ALWAYS

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  port: 10100
