spring:  
  application:
    name: product-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  config:
    import: optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  port: 10400
#---
#spring:
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone1
#  config:
#    activate:
#      on-profile: zone1
#---
#spring:
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone2
#  config:
#    activate:
#      on-profile: zone2